### ISSUE TITLE
use Object.values()

### ISSUE THREAD

**Issue by moaezzTM** [Omarzikry/Burger-Builder-React-App#4]
https://github.com/Omarzikry/Burger-Builder-React-App/blob/c59eca0736cb991baa1370e0ab9cbe76896ae0de/src/containers/BurgerBuilder/BurgerBuilder.js#L42
`Object.keys` is very useful to do operations on objects specially when mixing it will the array helps. 
but for the purpose of this function since you're just need the sum of the object values you can use `Object.values()` instead on mapping the keys to return the values.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values

**Comment by Omarzikry** [comment]
thanks, It really made a difference.
