### ISSUE TITLE
Dynamic controls.

### ISSUE THREAD

**Issue by moaezzTM** [Omarzikry/Burger-Builder-React-App#6]
https://github.com/Omarzikry/Burger-Builder-React-App/blob/c59eca0736cb991baa1370e0ab9cbe76896ae0de/src/components/Burger/BuildControls/BuildControls.js#L6

instead of hard coding the controls array why not have a single source of truce, the API response. you can use the API response to formulate the controls object. that way you don't have to worry about manually updating the controls object when you the API response is updated.

a good rule to follow, is always try to have a single source of truth to avoid bugs and extra work of syncing data.

**Comment by Omarzikry** [comment]
thanks, But I am currently making a demo It will surely be updated in the future
